### ISSUE TITLE
Setup CI/CD pipeline with linters/test suite runner

### ISSUE THREAD

**Issue by t-botclive** [topology-foundation/gram#10]
**Describe the problem you are trying to solve**
We need to have automated checks for each PR submitted. This check will run linter to check that code is properly formatted, best practices are followed and etc. Also tests command will be executed to verify that all existing tests are passing.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe why the solution is optimal**
A clear and concise description of the rationale for the solution you're proposing.

**Additional context**

**Comment by jihoonsong** [comment]
Could you fill in the template so people can understand what this issue is about?
