### ISSUE TITLE
Make gram configurable

### ISSUE THREAD

**Issue by jihoonsong** [topology-foundation/gram#6]
**Describe the problem you are trying to solve**
Currently, `gram` is not configurable when it gets instantiated. Make params such as `namespace`, `topics`, `port`, and `maxPeers` configurable. (See `/config/config.go` and `NewP2P` function of `/network/p2p.go` for more information.)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe why the solution is optimal**
A clear and concise description of the rationale for the solution you're proposing.

**Additional context**

**Comment by 0xMugen** [comment]
I can work on this. I feel relatively familiar with the code base now. Is a simple config file good?
